services:
    opensoft_onp_web.checks.local_storage:
        class: Opensoft\StorageBundle\Check\LocalStorageCheck
        public: false
        arguments:
            - '@doctrine'
            - '@storage_manager'
            - '@opensoft_onp_core.storage.gaufrette_adapter_resolver'
        tags:
            - { name: 'liip_monitor.check', alias: 'local_storage' }

    storage_manager:
        class: Opensoft\StorageBundle\Storage\StorageManager
        arguments:
            - '@doctrine'
            - '@opensoft_onp_core.storage.gaufrette_adapter_resolver'
            - '@storage.url_resolver'
            - '@storage.key_generator'

    opensoft_onp_core.storage.gaufrette_adapter_resolver:
        class: Opensoft\StorageBundle\Storage\GaufretteAdapterResolver

    storage.url_resolver:
        class: Opensoft\StorageBundle\Storage\StorageUrlResolver
        public: false
        arguments:
            - '@opensoft_onp_core.storage.gaufrette_adapter_resolver'

    storage.key_generator:
        class: Opensoft\StorageBundle\Storage\StorageKeyGenerator
        public: false

    storage.twig_url_extension:
        class: Opensoft\StorageBundle\Twig\Extension\StorageUrlExtension
        public: false
        arguments:
            - '@storage.url_resolver'
        tags:
            - { name: 'twig.extension' }

    storage.form_type.storage_adapter_options_type:
        class: Opensoft\StorageBundle\Form\Type\StorageAdapterOptionsType
        arguments:
            - '@opensoft_onp_core.storage.gaufrette_adapter_resolver'
        tags:
            - { name: 'form.type' }

    storage.form_type.stored_files_filter_type:
        class: Opensoft\StorageBundle\Form\Type\StoredFilesFilterType
        arguments:
            - '@opensoft_storage.storage_type_provider'
        tags:
            - { name: 'form.type' }

    storage.doctrine_event_subscriber:
        class: Opensoft\StorageBundle\EventListener\StorageListener
        public: false
        arguments:
            - '@storage_manager'
            - '@logger'
        tags:
            - { name: 'doctrine.event_subscriber', lazy: true }
            - { name: 'monolog.logger', channel: 'storage'}

    storage.adapter.aws_s3:
        class: Opensoft\StorageBundle\Storage\Adapter\AwsS3AdapterConfiguration
        public: false
        arguments:
            - '@router'
            - '%permanent.base_url%'
        tags:
            - { name: 'onp.storage_adapter' }

    storage.adapter.local:
        class: Opensoft\StorageBundle\Storage\Adapter\LocalAdapterConfiguration
        public: false
        arguments:
            - '@router'
            - '@assets.packages'
            - '%permanent.base_url%'
        tags:
            - { name: 'onp.storage_adapter' }
